### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by timothyshelton** [tmobile/docinator#10]
Latest commit has an issue with the `npm build` step.

Repro: `docker build -t docinator .`

Expected: docker container!

Actual:
```
#20 10.14 src/cli.ts(26,3): error TS2339: Property 'option' does not exist on type 'void'.
#20 10.14 src/cli.ts(39,3): error TS2339: Property 'option' does not exist on type 'void'.
```

**Comment by jamestharpe** [comment]
Reproduced. I'll see if I can get a fix up shortly.

**Comment by timothyshelton** [comment]
lgtm -- that branch builds fine.  THANKS!
